window.siteConfig = {
  comingSoon: true,
  title: "FUR:RAID 2026",
  locales: {
    ko: {
      comingSoonTitle: "곧 공개됩니다.",
      comingSoonPageTitle: "FUR:RAID 2026 | 곧 공개",
      pageTitle: "FUR:RAID 2026 메인 테마곡",
      eyebrow: "메인 테마곡 · 컬래버레이션",
      description: "SNOWRICE STUDIO와 함께 만든\nFUR:RAID 2026의 메인 테마곡입니다.",
      upcoming: "공개 예정",
      empty: "스트리밍 링크를 준비하고 있어요.",
      services: "스트리밍 서비스",
      player: "Spotify 음원 플레이어",
      language: "언어",
      nativeName: "한국어",
    },
    en: {
      comingSoonTitle: "Coming soon.",
      comingSoonPageTitle: "FUR:RAID 2026 | Coming Soon",
      pageTitle: "FUR:RAID 2026 Main Theme",
      eyebrow: "MAIN THEME · COLLABORATION",
      description: "The main theme for FUR:RAID 2026,\ncreated with SNOWRICE STUDIO.",
      upcoming: "Coming soon",
      empty: "Streaming links are being prepared.",
      services: "Streaming services",
      player: "Spotify music player",
      language: "Language",
      nativeName: "English",
    },
    ja: {
      comingSoonTitle: "近日公開。",
      comingSoonPageTitle: "FUR:RAID 2026 | 近日公開",
      pageTitle: "FUR:RAID 2026 メインテーマ曲",
      eyebrow: "メインテーマ曲 · コラボレーション",
      description: "SNOWRICE STUDIOと共同制作した\nFUR:RAID 2026のメインテーマ曲です。",
      upcoming: "公開予定",
      empty: "配信リンクを準備しています。",
      services: "音楽配信サービス",
      player: "Spotify音楽プレーヤー",
      language: "言語",
      nativeName: "日本語",
    },
  },
  spotifyPlayerUrl: "",
  streams: [
    { name: "Spotify", icon: "./assets/icons/spotify.png", url: "" },
    { name: "Apple Music", icon: "./assets/icons/apple-music.png", url: "" },
    { name: "YouTube Music", icon: "./assets/icons/youtube-music.png", url: "" },
    { name: "LINE MUSIC", icon: "./assets/icons/line-music.png", url: "" },
    { name: "Amazon Music", icon: "./assets/icons/amazon-music.png", url: "" },
    { name: "iTunes", icon: "./assets/icons/itunes-color.png", url: "" },
  ],
};
